apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: default
  labels:
    app: registry
spec:
  type: NodePort
  ports:
   - port: 30001
     protocol: TCP
     targetPort: 5000
     nodePort: 30001
     name: port-registry
  selector:
   app: registry
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registry
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: registry
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5000
              name: port-registry